### ISSUE TITLE
miniprogram-slim analyzer -t 报错  Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by caocong1** [wechat-miniprogram/miniprogram-slim#14]
```
√ analyze app.json success, used 102ms
√ analyzer subpackages success, used 210ms
√ analyzer pages success, used 122ms
- find unusedFilesC:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\handler\analyzerComp.js:45
    const size = allFileInfo[file].size
                                   ^

TypeError: Cannot read property 'size' of undefined
    at C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\handler\analyzerComp.js:45:36
    at Array.forEach (<anonymous>)
    at computeComponentSize (C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\handler\analyzerComp.js:44:17)
    at C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\utils\unused.js:77:18
    at Array.forEach (<anonymous>)
    at findAllComponentDeps (C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\utils\unused.js:75:14)
    at Command.genAppDepsGraph (C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\src\depsAnalyzer\index.js:94:25)
    at Command.listener (C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\node_modules\commander\index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\caoco\AppData\Roaming\npm\node_modules\miniprogram-slim\node_modules\commander\index.js:892:12)
```

**Comment by jianghao08** [comment]
I encountered the same error

**Comment by HaowenLee** [comment]
+1

**Comment by justin201802** [comment]
遇到同样的错误

**Comment by jiaweri** [comment]
遇到同样的错误
